#=================================================
# https://github.com/zhangsean/k8s-descheduler-mirror
# Description: Auto check latest descheduler release and tag docker image zhangsean/descheduler using GitHub Actions
# License: Apache V2.0
# Author: ZhangSean
#=================================================

name: Follow up descheduler release

on:
  schedule:
    - cron: 1 0 * * *
  watch:
    types: [started]
    if: github.event.repository.owner.id == github.event.sender.id
  push:
    paths:
      - '.github/workflows/*.yml'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Check new release
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          git fetch --tags
          export CURRENT=$(cat Dockerfile | awk -F: '{print $2}')
          echo "CURRENT=$CURRENT"
          export LATEST=$(curl -I https://github.com/kubernetes-sigs/descheduler/releases/latest | sed -n '/tag/s/.*tag\/\(v.*\)./\1/p')
          echo "LATEST=$LATEST"
          if [ "$LATEST" != "$CURRENT" ]; then
            echo "New descheduler released: $LATEST"
            echo "CURRENT=$CURRENT" >> $GITHUB_ENV
            echo "LATEST=$LATEST" >> $GITHUB_ENV
          else
            echo "No new descheduler released"
            echo "LATEST=" >> $GITHUB_ENV
          fi

      - name: Bump to new tag
        if: success() && env.CURRENT != '' && env.LATEST != ''
        env:
          DEBIAN_FRONTEND: noninteractive
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Changing tag from $CURRENT to $LATEST"
          sed -i "s/$CURRENT/$LATEST/g" README.md
          sed -i "s/$CURRENT/$LATEST/g" Dockerfile
          git config user.email zxf2342@qq.com
          git config user.name zhangsean
          git commit -a -m "Bump to descheduler $LATEST"
          git push

      - name: Create new release
        uses: actions/create-release@v1
        if: success() && env.CURRENT != '' && env.LATEST != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.LATEST }}
          release_name: ${{ env.LATEST }}
          body: |
            Bump to descheduler ${{ env.LATEST }}
          draft: false
          prerelease: false
